# gen_font.cmake
# Converts a binary font file into a C source file containing the data as a
# const byte array.  This satisfies the INCBIN_EXTERN(debug_font) declaration
# in lib/debug.c without needing GNU assembler's .incbin on PC.
#
# Usage (invoked by CMakeLists.txt add_custom_command):
#   cmake -DFONT_BIN=<path/to/Spectrum.bin> -DOUT_C=<path/to/out.c> -P gen_font.cmake

if(NOT FONT_BIN OR NOT OUT_C)
    message(FATAL_ERROR "gen_font.cmake: FONT_BIN and OUT_C must be set")
endif()

file(READ "${FONT_BIN}" hex_data HEX)

# Split hex string into pairs, then join with ", 0x" separator.
string(REGEX MATCHALL "[0-9a-fA-F][0-9a-fA-F]" hex_list "${hex_data}")
list(LENGTH hex_list font_size)
list(JOIN hex_list ", 0x" font_bytes)

file(WRITE "${OUT_C}"
"/* AUTO-GENERATED by gen_font.cmake — do not edit */\n"
"#include <stdint.h>\n"
"\n"
"const unsigned char debug_font_data[] = { 0x${font_bytes} };\n"
"const unsigned char * const debug_font_end  = debug_font_data + ${font_size};\n"
"const unsigned int          debug_font_size = ${font_size};\n"
)

message(STATUS "gen_font: wrote ${font_size} bytes to ${OUT_C}")
